// This file serves as a placeholder to satisfy Swift Package Manager's requirement
// that a target must have at least one Swift source file.
//
// The actual API client code is generated by the OpenAPI Generator plugin at build time
// from the openapi.json and openapi-generator-config.yaml files in this directory.
//
// Generated files include:
// - Types.swift: All request/response models from the OpenAPI spec
// - Client.swift: Type-safe methods for all API endpoints
//
// The generated code is internal to this module and re-exported for use by the app.

import Foundation

@_exported import HTTPTypes

// Re-export OpenAPI types for convenience when importing APIClient
@_exported import OpenAPIRuntime
@_exported import OpenAPIURLSession
